import { clsx, type ClassValue } from 'clsx'
import { twMerge } from 'tailwind-merge'

/**
 * Merge Tailwind classes safely, resolving conflicts (e.g. p-2 + p-4 → p-4).
 * Generated by shadcn/ui — do not modify.
 */
export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs))
}
